#!/bin/bash -uef

# REMOVE THIS IF YOU'RE USING A SINGLE DESKTOP ENVIRONMENT
# Code takes a guess at the current desktop environment.
# This is used to decide the wallpaper switching mechanism.
for de in i3 lxde ; do
    pgrep ${de} > /dev/null 2>&1
    if [[ $? -eq 0 ]]
    then
        break
    else
        de=none
    fi
done

# Set source folder for wallpapers.
# Users will likley only need to edit this line.
src="${HOME}/Pictures/Wallpapers/Use/"

# Method to get list of files.
# Gets all files in the src directory.
search="find ${src} -type f -readable -iname *.jpg -o -iname *.png -o -iname *.jpeg -o \
-iname *.bmp"

# Count the number of pictures we can use.
wallpaper_count=$(${search} | wc -l)

# Lockfile used to prevent wallpapers repeating.
lockfile="/var/lock/wallpaper.lock"
# Try to make the lockfile - will fall over if we don't have write permission.
touch "${lockfile}"

# Get the name of the last wallpaper.
lastpaper=$(cat "${lockfile}")

# Fall over if less than 2 wallpapers, there's nothing to shuffle.
if [[ ${wallpaper_count} -lt 2 ]]
then
    exit 1
fi

# Flag for ensuring the next wallpaper is new.
duplicate=1
loops=0

# Keep trying until we either time out, or get a new wallpaper.
while [[ ${duplicate} -eq 1 && loops -lt 5 ]]
do
    # Count up to make sure we don't go round forever.
    ((loops+=1))

    # List the files, shuffle them, pick one.
    img="$(${search} | shuf -n 1)"

    # Check the file we want to use is readable.
    if [[ ! -r ${img} ]]
    then
        # If not, try again.
        continue
    fi

    # If it's a new wallpaper, drop from the loop.
    if [[ ! "${img}" == "${lastpaper}" ]]
    then
        duplicate=0
    fi
done

# If it is a duplicate, don't bother trying to update.
if [[ ${duplicate} -eq 1 ]]
then
    exit 1
fi

# Update the lockfile.
echo ${img} > ${lockfile}

# Set the environment to run pcmanfm, and use it to set the wallpaper.
if [[ "$de" == "i3" ]]
then
    env DISPLAY=":0.0" feh --bg-scale "${img}"
elif [[ "$de" == "lxde" ]]
then
    env DISPLAY=":0.0" pcmanfm -w "${img}"
fi

# All done!
exit 0
